spring:
  redis:
    host: localhost
    cluster:
      nodes:
        - localhost:6380
        - localhost:6381
        - localhost:6382
        - localhost:6383
        - localhost:6384
        - localhost:6385
#logging:
#  level:
#    org.apache.kafka.clients: ERROR