spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848
---
spring:
  config:
    activate:
      on-profile: pro
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 192.168.1.11:8848
  #    import:
  #      - optional:nacos:${spring.application.name}:${spring.profiles.active}
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 192.168.1.20:8848
  #    import:
  #      - optional:nacos:${spring.application.name}:${spring.profiles.active}
---
spring:
  alarm:
    dingtalk:
      enabled: true
      # 钉钉群机器人唯一的token
      token: xxxxxx
      # 安全设置：加签的密钥
      secret: xxxxxxx
    wechat:
      enabled: true
      # 企业微信群机器人唯一key
      key: 629f44b3-f0d3-4438-9d01-27b09269c5c0
      # 被@人的手机号
      to-user: 15603397887
    mail:
      enabled: true
      smtpHost: smtp.qq.com
      smtpPort: 465
      to: zhazhafei@aliyun.com
      from: 1623285565@qq.com
      username: 1623285565@qq.com
      password: "ophlijooeeadbcid"
      ssl: true
      debug: true
    template:
      # 开启通过模板配置
      enabled: true
      # 配置模板来源为文件 枚举类：JDBC（数据库）、FILE（配置文件）、MEMORY（内存），目前只支持FILE，其他两种可自行扩展
      source: FILE
      # 配置模板数据 map
      templates:
        errorTemp:
          templateId: errorTemp
          templateName: 服务异常模板
          templateContent: 这里是配置模板的内容
        holidayErrorTemp:
          templateId: holidayErrorTemp
          templateName: 节假日获取失败
          templateContent: 请检查节假日接口是否正常
management:
  endpoints:
    web:
      exposure:
        include: "*" #打开所有的监控点
      base-path: /monitor
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    shutdown:
      enabled: true

ip:
  whitelist:
    addresses:
      - "192.168.1.1"
      - "192.168.1.8"
      - "192.168.1.11"
jwt:
  #  加密密钥
  secret: yangfei
  header: Authorization
  #  token有效时长 s
  expire:
    accessToken: 7200
    refreshToken: 604800
limit:
#  type: redis
  type: local

sys:
  web:
    filterNullAttr: true